...

diff --git a/bin/elevate b/bin/elevate
--- a/bin/elevate
+++ b/bin/elevate
@@ -1,37 +1,27 @@
 #!/usr/bin/env bash
-# ------------------------------------------------------------------------ INFO
-# [/.ael/bin/elevate]
-# author        : Pascal Malouin (https://github.com/alterEGO-Linux)
-# created       : 2023-08-02 00:10:38 UTC
-# updated       : 2026-04-07 11:15:26 UTC
-# description   : Repeats last command with sudo, if forgotten.
+# =============================================================================
+# INFO
+# =============================================================================
+# [/bin/elevate]
+# 
+# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
+# Created     : 2023-08-02 00:10:38 UTC
+# Updated     : 2026-08-31 16:50:39 UTC
+# Description : Repeats last command with sudo, if forgotten.
+# -----------------------------------------------------------------------------
 
 elevate() {
 
-    local __args=("${@}")
-    local __arg
-    local __blue=$'\033[34m'
-    local __red=$'\033[31m'
-    local __reset=$'\033[0m'
+    source ${HOME}/.ael/lib/bash/ael
+    import applications messages
 
-    trap 'unset -f usage check_applications; trap - RETURN' RETURN
-
-    check_applications() {
-      local __app
-      for __app in "${@}"; do
-          if ! command -v $__app >/dev/null 2>&1; then
-                printf '%s\n' "${__red}[!]${__reset} ${__app} is not installed."
-                return 1
-            fi
-        done
-    }
     check_applications bash sudo || return 1
 
     usage() {
         cat <<EOF
-================================================================================
+===============================================================================
 [+] elevate - Repeats last command with sudo, if forgotten.
-================================================================================
+===============================================================================
 Usage:
   elevate [--interactive][--help]
 
@@ -44,13 +34,14 @@ Options:
 
 IMPORTANT:
   This script must be sourced, otherwise history won't act as intented.
-================================================================================
+-------------------------------------------------------------------------------
 EOF
     }
 
-    local __command=$(history -p !!)
+    local __args=("${@}")
+    local __arg
 
-    # --- help
+    # --- help ----------------------------------------------------------------
     for __arg in "${__args[@]}"; do
         if [ "${__arg}" == '-h' ] || [ "${__arg}" == '--help' ]; then
             usage
@@ -58,31 +49,33 @@ EOF
         fi
     done
 
-    # --- Interactive.
+    # --- interactive ---------------------------------------------------------
     # ... Will exit in non-interactive context.
     
     local __input
+
+    message banner "elevate - Repeats last command with sudo, if forgotten."
     for __arg in "${__args[@]}"; do
         if [[ "${__arg}" == '-i' ]] || [[ "${__arg}" == '--interactive' ]]; then
             if [[ ! -t 0 ]]; then
-                printf '%s\n' "${__red}[!]${__reset} No interactive terminal available for confirmation prompt." >&2
+                message error "No interactive terminal available for confirmation prompt." >&2
                 return 1
             fi
-            printf "${__blue}[?]${__reset} Are you sure you want to proceed? [y/N] "
+            message step "Are you sure you want to proceed? [y/N] "
             read -r __input
                 if [[ "${__input}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
-                    sudo bash -c "${__command}"
+                    sudo bash -c "$(history -p !!)"
                     return 0
                 else
-                    printf '%s\n' "${__red}[!]${__reset} Aborting running '${__command}' with elevated privileges."
+                    message error "Aborting running last command with elevated privileges."
                     return 1
                 fi
         fi
     done
 
-    sudo bash -c "${__command}"
+    sudo bash -c "$(history -p !!)"
 }
 
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
-    usage --help
+    elevate --help
 fi
