...

diff --git a/shellutils/deep-nmap b/shellutils/deep-nmap
--- a/shellutils/deep-nmap
+++ b/shellutils/deep-nmap
@@ -1,22 +1,20 @@
 #!/usr/bin/env bash
-# :----------------------------------------------------------------------- INFO
-# :[~/.ael/shellutils/deep-nmap]
-# :author        : AlterEGO Linux
-# :created       : 2021-03-19 09:37:19 UTC
-# :updated       : 2025-08-14 11:12:55 UTC
-# :description   : Deep Nmap scan.
+# ------------------------------------------------------------------------ INFO
+# [shellutils/deep-nmap]
+# author        : Pascal Malouin @https://github.com/alterEGO-Linux
+# created       : 2025-12-22 02:05:30 UTC
+# updated       : 2025-12-22 02:05:30 UTC
+# description   : Deep Nmap scan.
 
 deep-nmap() {
 
+    # --- ( shell clean up )
     local ARGUMENTS_INPUT=("${@}")
 
-    # :: Unsetting functions to clean shell.
-    unsetter() {
-        unset -f usage
-        unset -f unsetter
-    }
+    trap '
+        unset -f usage; trap - RETURN' RETURN
 
-    # :: help / usage / documentation.
+    # --- ( help )
     usage() {
         cat <<EOF
 ================================================================================
@@ -40,22 +38,20 @@ Examples:
 EOF
     }
 
-    # :: No arguments.
+    # --- no arguments.
     if [[ $# == 0 ]]; then
         ARGUMENTS_INPUT=("-h")
     fi
 
-    # :: Show help and ignore other arguments.
+    # --- show help and ignore other arguments.
     local i
     for i in "${ARGUMENTS_INPUT[@]}"; do
         if [[ "${i}" == "-h" || "${i}" == "--help" ]]; then
             usage
-            unsetter
             return 0
         fi
     done
 
     sudo grc nmap -sV -O -sC --traceroute "$@"
-    unsetter
     return 0
 }
diff --git a/shellutils/deep-scan b/shellutils/deep-scan
--- a/shellutils/deep-scan
+++ b/shellutils/deep-scan
@@ -1,13 +1,14 @@
 #!/usr/bin/env bash
-# :----------------------------------------------------------------------- INFO
-# :[~/.ael/shellutils/deep-scan]
-# :author        : AlterEGO Linux
-# :created       : 2023-10-20 09:10:13 UTC
-# :updated       : 2025-08-15 10:27:40 UTC
-# :description   : Scans IP with rustscan and nmap.
+# ------------------------------------------------------------------------ INFO
+# [shellutils/deep-scan]
+# author        : Pascal Malouin @https://github.com/alterEGO-Linux
+# created       : 2023-10-20 09:10:13 UTC
+# updated       : 2025-12-22 02:09:58 UTC
+# description   : Scans IP with rustscan and nmap.
 
 deep-scan() {
 
+    # --- shell clean up.
     local BLUE=$'\033[34m'
     local RED=$'\033[31m'
     local RESET=$'\033[0m'
@@ -15,9 +16,10 @@ deep-scan() {
     local NMAP
     local PORTS
 
-    trap 'unset -f _ds_check_applications _ds_usage; trap - RETURN' RETURN
+    trap 'unset -f check_applications usage; trap - RETURN' RETURN
 
-    _ds_check_applications() {
+    check_applications() {
+        # --- verify applications on system.
 
         local app
         local apps=("$@")
@@ -35,7 +37,7 @@ deep-scan() {
         fi
     }
 
-    _ds_usage() {
+    usage() {
         cat <<EOF
 ================================================================================
 [+] deep-scan - Scans IP with rustscan and nmap.
@@ -54,42 +56,42 @@ Examples:
 EOF
     }
 
-    # :: Check applications.
-    if ! _ds_check_applications rustscan nmap sudo; then
+    # --- check applications.
+    if ! check_applications rustscan nmap sudo; then
         return 1
     fi
 
-    # :: Setting IP value.
+    # --- setting IP value.
     IP="${1:-127.0.0.1}"
     [[ "$IP" == "localhost" ]] && IP="127.0.0.1"
 
-    # :: Show help and ignore other arguments.
+    # --- show help and ignore other arguments.
     local i
     for i in "${@}"; do
         if [[ "${i}" == "-h" || "${i}" == "--help" ]]; then
-            _ds_usage
+            usage
             return 0
         fi
     done
 
-    # :: Too many arguments.
+    # --- too many arguments.
     if [[ $# -gt 1 ]]; then
         printf '%s\n' "${RED}[!]${RESET} Too many arguments."
-        _ds_usage
+        usage
         return 1
     fi
 
-    # :: Rustscan.
+    # --- rustscan.
     printf '%s\n' "${BLUE}[+]${RESET} Running Rustscan to find open ports."
 
     PORTS=$(rustscan -a "$IP" --ulimit 5000 --batch-size 2000 --greppable | grep -oP '\[\K[0-9,]+(?=\])')
 
-    # :: Nmap.
+    # --- nmap.
     if [[ -n "${PORTS}" ]]; then
         printf '%s\n' "${BLUE}[-]${RESET} Found ${PORTS}."
         printf '%s\n' "${BLUE}[+]${RESET} Running Nmap."
 
-        # :: Check grc availability.
+        # --- check grc availability.
         if command -v grc >/dev/null 2>&1; then
             NMAP=(grc nmap)
         else
diff --git a/shellutils/elevate b/shellutils/elevate
--- a/shellutils/elevate
+++ b/shellutils/elevate
@@ -1,20 +1,23 @@
 #!/usr/bin/env bash
-# :----------------------------------------------------------------------- INFO
-# :[~/.ael/shellutils/elevate]
-# :author        : AlterEGO Linux
-# :created       : 2023-08-02 00:10:38 UTC
-# :updated       : 2025-07-09 20:26:12 UTC
-# :description   : Repeats last command with sudo, if forgotten.
+# ------------------------------------------------------------------------ INFO
+# [shellutils/elevate]
+# author        : Pascal Malouin @https://github.com/alterEGO-Linux
+# created       : 2023-08-02 00:10:38 UTC
+# updated       : 2025-12-22 03:05:26 UTC
+# description   : Repeats last command with sudo, if forgotten.
 
 elevate() {
 
+    # --- shell clean up
     local __args=("${@}")
     local __arg
     local BLUE=$'\033[34m'
     local RED=$'\033[31m'
     local RESET=$'\033[0m'
 
-    elevate-usage() {
+    trap 'unset -f usage; trap - RETURN' RETURN
+
+    usage() {
         cat <<EOF
 ================================================================================
 [+] elevate - Repeats last command with sudo, if forgotten.
@@ -33,17 +36,15 @@ EOF
 
     local __command=$(history -p !!)
 
-    # :-( help )
+    # --- help
     for __arg in "${__args[@]}"; do
         if [ "${__arg}" == '-h' ] || [ "${__arg}" == '--help' ]; then
-            elevate-usage
-            unset -f elevate-usage
+            usage
             return 0
         fi
     done
 
     local __input
-
     for __arg in "${__args[@]}"; do
         if [[ "${__arg}" == '-i' ]] || [[ "${__arg}" == '--interactive' ]]; then
             read -p "${BLUE}[?]${RESET} Are you sure you want to proceed? [y/N] " __input
